apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::224687663134:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters

    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::224687663134:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1VKE5Q48KA1B8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-22T19:44:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "807"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e27511df-a396-4184-bda4-7e411abde4e3
