apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::224687663134:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-14CSY2HQG0E97
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-24T00:10:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "933"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 55103382-9d5a-464c-b019-0a5961efb325
